name: This is a bug
description: Tell me your bugs
title: ":bug: [Bug]: <ADD TITLE HERE>"
labels: [bug, triage]
assignees:
  - mishmanners
body:
  - type: markdown
    attributes:
      value: 
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value:
    validations:
      required: true
